#include "ParapentingGameMode.h"
#include "ParapentingHUD.h"
#include "ParagliderPawn.h"
#include "ParapentingTerrain.h"
#include "Components/DirectionalLightComponent.h"
#include "Components/ExponentialHeightFogComponent.h"
#include "Components/SkyLightComponent.h"
#include "Components/SkyAtmosphereComponent.h"
#include "Components/StaticMeshComponent.h"
#include "Components/HierarchicalInstancedStaticMeshComponent.h"
#include "Components/VolumetricCloudComponent.h"
#include "ProceduralMeshComponent.h"
#include "Engine/DirectionalLight.h"
#include "Engine/ExponentialHeightFog.h"
#include "Engine/SkyLight.h"
#include "Engine/StaticMeshActor.h"
#include "Engine/World.h"
#include "GameFramework/HUD.h"
#include "GameFramework/PlayerController.h"
#include "Materials/MaterialInstanceDynamic.h"
#include "EngineUtils.h"
#include "Physics/TerrainModel.h"
#include "Physics/RouteCatalogue.h"
#include "Physics/WindsockModel.h"
#include "UObject/ConstructorHelpers.h"
#include "HAL/FileManager.h"
#include "HAL/PlatformMisc.h"
#include "ImageUtils.h"
#include "Misc/CommandLine.h"
#include "Misc/FileHelper.h"
#include "Misc/Parse.h"
#include "Misc/Paths.h"
#include "UnrealClient.h"

AParapentingGameMode::AParapentingGameMode()
{
    PrimaryActorTick.bCanEverTick = true;
    PrimaryActorTick.TickInterval = 0.2f;
    DefaultPawnClass = AParagliderPawn::StaticClass();
    HUDClass = AParapentingHUD::StaticClass();
}

void AParapentingGameMode::InitGame(
    const FString& MapName, const FString& Options, FString& ErrorMessage)
{
    Super::InitGame(MapName, Options, ErrorMessage);

    bVisualQACaptureRequested = FParse::Value(
        FCommandLine::Get(), TEXT("VisualQACapture="), VisualQACaptureName);
    FString VisualQAHourText;
    if (FParse::Value(
            FCommandLine::Get(), TEXT("VisualQAHour="), VisualQAHourText))
    {
        VisualQALocalHour = FCString::Atod(*VisualQAHourText);
    }
    FParse::Value(
        FCommandLine::Get(), TEXT("VisualQAWarmup="), VisualQAWarmupSeconds);
    FParse::Value(
        FCommandLine::Get(), TEXT("VisualQAWeatherPreset="),
        VisualQAWeatherPreset);
    VisualQAWarmupSeconds = FMath::Max(1.0f, VisualQAWarmupSeconds);

    // InitGame runs before the default pawn is spawned. Loading the
    // authoritative terrain here guarantees the pawn's BeginPlay/ResetFlight
    // queries the surveyed launch elevation rather than the analytic fallback.
    // Both surveyed regions, in one shared route frame. Loading is additive
    // and the regions do not overlap, so which one answers for a sample is
    // decided by position rather than by load order or by the active route.
    bLoadedSurveyedTerrain = true;
    for (const TCHAR* RegionFile :
             {TEXT("Terrain/interlaken.asc"), TEXT("Terrain/grindelwald.asc")})
    {
        const FString HeightfieldPath = FPaths::Combine(
            FPaths::ProjectContentDir(), RegionFile);
        const bool bLoaded =
            Parapenting::Physics::TerrainModel::LoadHeightfieldAscii(
                TCHAR_TO_UTF8(*HeightfieldPath));
        bLoadedSurveyedTerrain = bLoadedSurveyedTerrain && bLoaded;
        UE_LOG(LogTemp, Display, TEXT("Parapenting terrain region: %s (%s)"),
            bLoaded ? TEXT("surveyed swissALTI3D") : TEXT("MISSING"),
            *HeightfieldPath);
    }
}

void AParapentingGameMode::BeginPlay()
{
    Super::BeginPlay();

    UWorld* World = GetWorld();
    if (!World) return;

    // The map may contain editor-authored preview suns. Forward shading can
    // only choose one primary directional light, so remove those before
    // creating the single simulation-controlled atmosphere sun.
    for (TActorIterator<ADirectionalLight> It(World); It; ++It)
        It->Destroy();
    for (TActorIterator<ASkyLight> It(World); It; ++It)
        It->Destroy();
    for (TActorIterator<AExponentialHeightFog> It(World); It; ++It)
        It->Destroy();
    for (TActorIterator<ASkyAtmosphere> It(World); It; ++It)
        It->Destroy();
    // The startup template also ships a legacy UE4-style SM_SkySphere and its
    // own volumetric cloud layer. The sky sphere is an ordinary static mesh,
    // so none of the clears above touch it: it survives as a giant opaque
    // dome drawn around the whole level, hiding the SkyAtmosphere behind a
    // flat gradient that no longer tracks the sun we spawn below. Remove both
    // so the atmosphere is the only sky.
    for (TActorIterator<AVolumetricCloud> It(World); It; ++It)
        It->Destroy();
    for (TActorIterator<AStaticMeshActor> It(World); It; ++It)
    {
        // Match the mesh asset, not the actor. "SM_SkySphere" is the Outliner
        // label; the actor's own name is an autogenerated StaticMeshActor_N,
        // so testing GetName() here silently matches nothing.
        const UStaticMeshComponent* Mesh = It->GetStaticMeshComponent();
        const UStaticMesh* Asset = Mesh ? Mesh->GetStaticMesh() : nullptr;
        if (Asset && Asset->GetName().Contains(TEXT("SkySphere")))
            It->Destroy();
    }
    ADirectionalLight* Sun = World->SpawnActor<ADirectionalLight>(
        FVector::ZeroVector, FRotator(-38.0, -28.0, 0.0));
    Sun->GetLightComponent()->SetIntensity(7.5f);
    Sun->GetLightComponent()->SetLightColor(FLinearColor(1.0f, 0.98f, 0.94f));
    Sun->GetLightComponent()->SetMobility(EComponentMobility::Movable);
    if (UDirectionalLightComponent* SpawnedSunComponent =
        Cast<UDirectionalLightComponent>(Sun->GetLightComponent()))
    {
        SunComponent = SpawnedSunComponent;
        SpawnedSunComponent->SetAtmosphereSunLight(true);
        SpawnedSunComponent->SetLightSourceAngle(1.2f);
        SpawnedSunComponent->SetDynamicShadowDistanceMovableLight(1800000.0f);
        SpawnedSunComponent->bCastCloudShadows = true;
        SpawnedSunComponent->CloudShadowStrength = 0.22f;
        SpawnedSunComponent->CloudShadowOnSurfaceStrength = 0.22f;
    }

    ASkyLight* Sky = World->SpawnActor<ASkyLight>();
    SkyLightComponent = Sky->GetLightComponent();
    // M_VertexLit removes the old fake key light from terrain vertex colours.
    // The previous 0.42 skylight then left every sun-facing-away slope close
    // to black. Alpine shade is cool and strongly sky-lit, not unilluminated:
    // use the atmosphere capture as the fill and retain a restrained lower-
    // hemisphere ground bounce for canopy undersides and steep valley walls.
    SkyLightComponent->SetIntensity(1.35f);
    SkyLightComponent->bLowerHemisphereIsBlack = false;
    SkyLightComponent->SetLowerHemisphereColor(
        FLinearColor(0.055f, 0.070f, 0.085f));
    SkyLightComponent->SetRealTimeCapture(true);
    SkyLightComponent->SetMobility(EComponentMobility::Movable);

    ASkyAtmosphere* AtmosphereActor = World->SpawnActor<ASkyAtmosphere>();
    USkyAtmosphereComponent* Atmosphere = AtmosphereActor->GetComponent();
    // These scales are absolute scattering coefficients in 1/km, not
    // multipliers. Earth's values are the component defaults: Rayleigh
    // 0.0331 and Mie 0.003996. Feeding 1.25 and 0.22 made the atmosphere
    // roughly forty times too dense, so all the blue scattered out within a
    // few kilometres and the sky read as a flat opaque orange at every time
    // of day. Stay near the physical values and express any artistic bias as
    // a small factor on them.
    constexpr float EarthRayleighScattering = 0.0331f;
    constexpr float EarthMieScattering = 0.003996f;
    // Clean, dry alpine air: slightly richer Rayleigh, noticeably less
    // aerosol haze than the global average.
    Atmosphere->SetRayleighScatteringScale(EarthRayleighScattering * 1.10f);
    Atmosphere->SetMieScatteringScale(EarthMieScattering * 0.75f);
    Atmosphere->SetMieAnisotropy(0.76f);

    AActor* CloudActor = World->SpawnActor<AActor>();
    UVolumetricCloudComponent* Clouds =
        NewObject<UVolumetricCloudComponent>(CloudActor, TEXT("AlpineClouds"));
    CloudComponent = Clouds;
    CloudActor->SetRootComponent(Clouds);
    Clouds->SetLayerBottomAltitude(2.2f);
    Clouds->SetLayerHeight(0.7f);
    if (UMaterialInterface* CloudMaterial = LoadObject<UMaterialInterface>(
        nullptr, TEXT("/Engine/EngineSky/VolumetricClouds/m_SimpleVolumetricCloud.m_SimpleVolumetricCloud")))
    {
        CloudMaterialInstance =
            UMaterialInstanceDynamic::Create(CloudMaterial, CloudActor);
        Clouds->SetMaterial(CloudMaterialInstance);
    }
    Clouds->RegisterComponent();

    AExponentialHeightFog* Fog = World->SpawnActor<AExponentialHeightFog>();
    FogComponent = Fog->GetComponent();
    FogComponent->SetFogDensity(0.00025f);
    FogComponent->SetFogHeightFalloff(0.12f);
    // Inscattering is a luminance, not a tint. At 0.55/0.72/0.88 the fog was
    // brighter than most of the terrain it covered, so it painted distant
    // ground pale blue and fought the atmosphere's own aerial perspective.
    // Keep it dim: the SkyAtmosphere supplies distance colour, and this layer
    // only adds valley haze on top.
    FogComponent->SetFogInscatteringColor(
        FLinearColor(0.055f, 0.075f, 0.105f));
    FogComponent->SetStartDistance(18000.0f);
    FogComponent->SetVolumetricFog(false);

    UStaticMesh* CylinderMesh = LoadObject<UStaticMesh>(
        nullptr, TEXT("/Engine/BasicShapes/Cylinder.Cylinder"));
    UStaticMesh* ConeMesh = LoadObject<UStaticMesh>(
        nullptr, TEXT("/Engine/BasicShapes/Cone.Cone"));
    UStaticMesh* SphereMesh = LoadObject<UStaticMesh>(
        nullptr, TEXT("/Engine/BasicShapes/Sphere.Sphere"));
    UStaticMesh* CubeMesh = LoadObject<UStaticMesh>(
        nullptr, TEXT("/Engine/BasicShapes/Cube.Cube"));
    UMaterialInterface* ShapeMaterial = LoadObject<UMaterialInterface>(
        nullptr, TEXT("/Engine/BasicShapes/BasicShapeMaterial.BasicShapeMaterial"));

    World->SpawnActor<AParapentingTerrain>();

    if (ConeMesh && CylinderMesh)
    {
        AActor* Forest = World->SpawnActor<AActor>();
        UHierarchicalInstancedStaticMeshComponent* Crowns =
            NewObject<UHierarchicalInstancedStaticMeshComponent>(Forest, TEXT("ForestCrowns"));
        UHierarchicalInstancedStaticMeshComponent* Trunks =
            NewObject<UHierarchicalInstancedStaticMeshComponent>(Forest, TEXT("ForestTrunks"));
        UHierarchicalInstancedStaticMeshComponent* Deciduous =
            NewObject<UHierarchicalInstancedStaticMeshComponent>(
                Forest, TEXT("DeciduousCrowns"));
        UHierarchicalInstancedStaticMeshComponent* ForestEdges =
            NewObject<UHierarchicalInstancedStaticMeshComponent>(
                Forest, TEXT("ForestEdgeConifers"));
        UHierarchicalInstancedStaticMeshComponent* Shrubs =
            NewObject<UHierarchicalInstancedStaticMeshComponent>(
                Forest, TEXT("ForestEdgeShrubs"));
        Forest->SetRootComponent(Crowns);
        Crowns->SetStaticMesh(ConeMesh);
        Trunks->SetupAttachment(Crowns);
        Trunks->SetStaticMesh(CylinderMesh);
        Deciduous->SetupAttachment(Crowns);
        Deciduous->SetStaticMesh(SphereMesh);
        ForestEdges->SetupAttachment(Crowns);
        ForestEdges->SetStaticMesh(ConeMesh);
        Shrubs->SetupAttachment(Crowns);
        Shrubs->SetStaticMesh(SphereMesh);
        Crowns->SetCollisionEnabled(ECollisionEnabled::NoCollision);
        Trunks->SetCollisionEnabled(ECollisionEnabled::NoCollision);
        Deciduous->SetCollisionEnabled(ECollisionEnabled::NoCollision);
        ForestEdges->SetCollisionEnabled(ECollisionEnabled::NoCollision);
        Shrubs->SetCollisionEnabled(ECollisionEnabled::NoCollision);
        Crowns->SetCullDistances(120000, 950000);
        Trunks->SetCullDistances(90000, 650000);
        Deciduous->SetCullDistances(100000, 750000);
        ForestEdges->SetCullDistances(100000, 1000000);
        Shrubs->SetCullDistances(70000, 500000);
        Crowns->RegisterComponent();
        Trunks->RegisterComponent();
        Deciduous->RegisterComponent();
        ForestEdges->RegisterComponent();
        Shrubs->RegisterComponent();
        if (ShapeMaterial)
        {
            UMaterialInstanceDynamic* CrownMaterial =
                UMaterialInstanceDynamic::Create(ShapeMaterial, Forest);
            CrownMaterial->SetVectorParameterValue(
                TEXT("Color"), FLinearColor(0.035f, 0.16f, 0.045f));
            Crowns->SetMaterial(0, CrownMaterial);
            UMaterialInstanceDynamic* TrunkMaterial =
                UMaterialInstanceDynamic::Create(ShapeMaterial, Forest);
            TrunkMaterial->SetVectorParameterValue(
                TEXT("Color"), FLinearColor(0.12f, 0.055f, 0.018f));
            Trunks->SetMaterial(0, TrunkMaterial);
            UMaterialInstanceDynamic* DeciduousMaterial =
                UMaterialInstanceDynamic::Create(ShapeMaterial, Forest);
            DeciduousMaterial->SetVectorParameterValue(
                TEXT("Color"), FLinearColor(0.075f, 0.24f, 0.045f));
            Deciduous->SetMaterial(0, DeciduousMaterial);
            UMaterialInstanceDynamic* ForestEdgeMaterial =
                UMaterialInstanceDynamic::Create(ShapeMaterial, Forest);
            ForestEdgeMaterial->SetVectorParameterValue(
                TEXT("Color"), FLinearColor(0.018f, 0.095f, 0.028f));
            ForestEdges->SetMaterial(0, ForestEdgeMaterial);
            UMaterialInstanceDynamic* ShrubMaterial =
                UMaterialInstanceDynamic::Create(ShapeMaterial, Forest);
            ShrubMaterial->SetVectorParameterValue(
                TEXT("Color"), FLinearColor(0.065f, 0.20f, 0.042f));
            Shrubs->SetMaterial(0, ShrubMaterial);
        }

        for (int32 XIndex = -10; XIndex <= 48; ++XIndex)
        {
            for (int32 YIndex = -18; YIndex <= 18; ++YIndex)
            {
                const float X = XIndex * 85.0f
                    + FMath::Sin(XIndex * 9.17f + YIndex * 2.31f) * 28.0f;
                const float Y = YIndex * 95.0f
                    + FMath::Sin(YIndex * 5.73f - XIndex * 1.61f) * 33.0f;
                const float CorridorWidth = X < 850.0f ? 230.0f : 520.0f;
                if (FMath::Abs(Y) < CorridorWidth) continue;
                const float Density = FMath::PerlinNoise2D(
                    FVector2D(X * 0.0031f, Y * 0.0031f));
                if (Density < -0.12f) continue;
                const float Ground = static_cast<float>(
                    Parapenting::Physics::TerrainModel::HeightM(X, Y));
                const auto GroundNormal =
                    Parapenting::Physics::TerrainModel::Normal(X, Y);
                // Keep water, landing basins and exposed steep faces readable.
                if (Ground < 12.0f || GroundNormal.z < 0.72) continue;
                const float HeightScale = 0.75f + 0.35f
                    * FMath::Abs(FMath::Sin(X * 0.017f + Y * 0.013f));
                const bool bDeciduous =
                    Ground < 480.0f && Density > 0.18f && SphereMesh;
                if (bDeciduous)
                {
                    Deciduous->AddInstance(FTransform(
                        FRotator::ZeroRotator,
                        FVector(X, Y, Ground + 8.0f) * 100.0f,
                        FVector(4.6f, 4.6f, 5.8f) * HeightScale));
                }
                else
                {
                    Crowns->AddInstance(FTransform(
                        FRotator::ZeroRotator,
                        FVector(X, Y, Ground + 8.5f) * 100.0f,
                        FVector(2.8f, 2.8f, 9.5f) * HeightScale));
                }
                Trunks->AddInstance(FTransform(
                    FRotator::ZeroRotator,
                    FVector(X, Y, Ground + 3.8f) * 100.0f,
                    FVector(0.45f, 0.45f, 7.6f) * HeightScale));
            }
        }

        // The flyable corridor needs an intentional edge: broken belts of
        // taller conifers and low shrubs make field clearings legible from the
        // air without adding obstacle clutter directly beneath the pilot.
        for (int32 XIndex = -8; XIndex <= 48; ++XIndex)
        {
            const float X = XIndex * 86.0f
                + FMath::Sin(XIndex * 6.31f) * 34.0f;
            const float CorridorWidth = X < 850.0f ? 230.0f : 520.0f;
            for (const float Side : {-1.0f, 1.0f})
            {
                const float EdgeNoise = 0.5f + 0.5f * FMath::PerlinNoise2D(
                    FVector2D(X * 0.0042f, Side * 17.0f));
                // Gaps avoid an artificial hedge and preserve approach views.
                if (EdgeNoise < 0.42f) continue;
                const float Y = Side * (CorridorWidth + 55.0f
                    + 125.0f * EdgeNoise);
                const float Ground = static_cast<float>(
                    Parapenting::Physics::TerrainModel::HeightM(X, Y));
                const auto Normal =
                    Parapenting::Physics::TerrainModel::Normal(X, Y);
                if (Ground < 12.0f || Normal.z < 0.76) continue;
                const float Scale = 0.85f + 0.30f * EdgeNoise;
                ForestEdges->AddInstance(FTransform(
                    FRotator(0.0f, XIndex * 23.0f, 0.0f),
                    FVector(X, Y, Ground + 10.0f) * 100.0f,
                    FVector(3.5f, 3.5f, 11.5f) * Scale));
                for (int32 ShrubIndex = 0; ShrubIndex < 3; ++ShrubIndex)
                {
                    const float OffsetX = (ShrubIndex - 1) * 19.0f
                        + FMath::Sin(XIndex * 3.1f + ShrubIndex) * 7.0f;
                    const float OffsetY = Side * (18.0f + ShrubIndex * 12.0f);
                    const float ShrubGround = static_cast<float>(
                        Parapenting::Physics::TerrainModel::HeightM(
                            X + OffsetX, Y + OffsetY));
                    Shrubs->AddInstance(FTransform(
                        FRotator::ZeroRotator,
                        FVector(X + OffsetX, Y + OffsetY,
                            ShrubGround + 1.5f) * 100.0f,
                        FVector(1.4f, 1.4f, 1.1f)
                            * (0.75f + 0.18f * ShrubIndex)));
                }
            }
        }
        // Sparse Grindelwald regional lane. It shares the global orientation
        // but is translated north so real wind bearings remain valid.
        for (int32 XIndex = -4; XIndex <= 56; ++XIndex)
        {
            for (int32 YIndex = 58; YIndex <= 98; ++YIndex)
            {
                const float X = XIndex * 85.0f
                    + FMath::Sin(XIndex * 7.31f + YIndex) * 24.0f;
                const float Y = -(YIndex * 90.0f
                    + FMath::Sin(YIndex * 3.97f - XIndex) * 29.0f);
                const float RouteY = -8500.0f + 0.547f * X;
                if (FMath::Abs(Y - RouteY) < 420.0f) continue;
                const float Density = FMath::PerlinNoise2D(
                    FVector2D(X * 0.0037f + 12.0f, Y * 0.0037f));
                if (Density < -0.08f) continue;
                const float Ground = static_cast<float>(
                    Parapenting::Physics::TerrainModel::HeightM(X, Y));
                const auto Normal =
                    Parapenting::Physics::TerrainModel::Normal(X, Y);
                if (Ground < 430.0f || Normal.z < 0.70) continue;
                const float Scale = 0.72f + 0.32f
                    * FMath::Abs(FMath::Sin(X * 0.014f + Y * 0.009f));
                Crowns->AddInstance(FTransform(
                    FRotator::ZeroRotator,
                    FVector(X, Y, Ground + 8.5f) * 100.0f,
                    FVector(2.8f, 2.8f, 9.5f) * Scale));
                Trunks->AddInstance(FTransform(
                    FRotator::ZeroRotator,
                    FVector(X, Y, Ground + 3.8f) * 100.0f,
                    FVector(0.45f, 0.45f, 7.6f) * Scale));
            }
        }
    }

    // Low-cost valley settlements give speed/height cues and make the Lehn
    // and Interlaken basins readable from approach altitude.
    if (CubeMesh && ShapeMaterial)
    {
        AActor* Settlements = World->SpawnActor<AActor>();
        UHierarchicalInstancedStaticMeshComponent* Buildings =
            NewObject<UHierarchicalInstancedStaticMeshComponent>(
                Settlements, TEXT("ValleyBuildings"));
        Settlements->SetRootComponent(Buildings);
        UHierarchicalInstancedStaticMeshComponent* Roofs =
            NewObject<UHierarchicalInstancedStaticMeshComponent>(
                Settlements, TEXT("ValleyRoofs"));
        Buildings->SetStaticMesh(CubeMesh);
        Roofs->SetupAttachment(Buildings);
        Roofs->SetStaticMesh(CubeMesh);
        Buildings->SetCollisionEnabled(ECollisionEnabled::NoCollision);
        Buildings->SetCullDistances(120000, 900000);
        Roofs->SetCollisionEnabled(ECollisionEnabled::NoCollision);
        Roofs->SetCullDistances(120000, 900000);
        Buildings->RegisterComponent();
        Roofs->RegisterComponent();
        UMaterialInstanceDynamic* BuildingMaterial =
            UMaterialInstanceDynamic::Create(ShapeMaterial, Settlements);
        BuildingMaterial->SetVectorParameterValue(
            TEXT("Color"), FLinearColor(0.52f, 0.45f, 0.36f));
        Buildings->SetMaterial(0, BuildingMaterial);
        UMaterialInstanceDynamic* RoofMaterial =
            UMaterialInstanceDynamic::Create(ShapeMaterial, Settlements);
        RoofMaterial->SetVectorParameterValue(
            TEXT("Color"), FLinearColor(0.24f, 0.075f, 0.035f));
        Roofs->SetMaterial(0, RoofMaterial);

        for (int32 Block = 0; Block < 170; ++Block)
        {
            const float X = 2050.0f + (Block % 34) * 105.0f
                + FMath::Sin(Block * 2.17f) * 28.0f;
            const float Y = 720.0f - (Block / 34) * 330.0f
                - FMath::Sin(Block * 4.71f) * 72.0f;
            const float Ground = static_cast<float>(
                Parapenting::Physics::TerrainModel::HeightM(X, Y));
            const auto Normal =
                Parapenting::Physics::TerrainModel::Normal(X, Y);
            if (Ground > 170.0f || Normal.z < 0.94) continue;
            const float BuildingHeight = 7.0f + 2.4f * (Block % 4);
            const float Width = 7.0f + 1.6f * (Block % 3);
            const float Depth = 5.0f + 1.2f * ((Block / 3) % 3);
            const float Yaw = static_cast<float>((Block * 37) % 180);
            Buildings->AddInstance(FTransform(
                FRotator(0.0f, Yaw, 0.0f),
                FVector(X, Y, Ground + BuildingHeight * 0.5f) * 100.0f,
                FVector(Width, Depth, BuildingHeight)));
            Roofs->AddInstance(FTransform(
                FRotator(0.0f, Yaw, 45.0f),
                FVector(X, Y, Ground + BuildingHeight + 1.2f) * 100.0f,
                FVector(Width * 0.78f, Depth * 0.78f, 1.8f)));
        }
        for (int32 Block = 0; Block < 120; ++Block)
        {
            const bool bBodmi = Block >= 80;
            const int32 Local = bBodmi ? Block - 80 : Block;
            const float X = (bBodmi ? 2860.0f : 3650.0f)
                + (Local % 10) * 72.0f
                + FMath::Sin(Block * 2.41f) * 18.0f;
            const float Y = (bBodmi ? -7180.0f : -6070.0f)
                - (Local / 10) * 88.0f
                - FMath::Sin(Block * 3.19f) * 24.0f;
            const float Ground = static_cast<float>(
                Parapenting::Physics::TerrainModel::HeightM(X, Y));
            const auto Normal =
                Parapenting::Physics::TerrainModel::Normal(X, Y);
            if (Normal.z < 0.88) continue;
            const float Height = 6.0f + 1.8f * (Block % 4);
            const float Width = 6.0f + 1.2f * (Block % 3);
            const float Depth = 5.0f + 1.1f * ((Block / 3) % 3);
            const float Yaw = static_cast<float>((Block * 29) % 180);
            Buildings->AddInstance(FTransform(
                FRotator(0.0f, Yaw, 0.0f),
                FVector(X, Y, Ground + Height * 0.5f) * 100.0f,
                FVector(Width, Depth, Height)));
            Roofs->AddInstance(FTransform(
                FRotator(0.0f, Yaw, 45.0f),
                FVector(X, Y, Ground + Height + 1.0f) * 100.0f,
                FVector(Width * 0.78f, Depth * 0.78f, 1.6f)));
        }
    }

    if (ShapeMaterial)
    {
        // Lake Thun lies route-right/west of the southbound Amisbuehl line,
        // which is +Y now that the frame is route-right. Its 558 m MSL
        // surface is approximately -7 m in the Lehn datum.
        AActor* Lake = World->SpawnActor<AActor>();
        UProceduralMeshComponent* LakeSurface =
            NewObject<UProceduralMeshComponent>(Lake, TEXT("LakeThunSurface"));
        Lake->SetRootComponent(LakeSurface);
        LakeSurface->SetCollisionEnabled(ECollisionEnabled::NoCollision);
        LakeSurface->SetCastShadow(false);
        LakeSurface->RegisterComponent();

        // A tapered shoreline silhouette replaces the kilometre-scale engine
        // plane whose rectangular edge drew a ruler-straight horizon through
        // the Amisbuehl corridor. Coordinates remain in the same surveyed
        // route frame and the water elevation remains -6.8 m in the Lehn
        // datum (558 m MSL).
        constexpr float LakeHeightCm = -680.0f;
        const TArray<FVector2D> ShoreM = {
            FVector2D(-900.0f, 1200.0f),
            FVector2D(-620.0f, 1880.0f),
            FVector2D(120.0f, 2110.0f),
            FVector2D(1040.0f, 2040.0f),
            FVector2D(1880.0f, 1760.0f),
            FVector2D(2310.0f, 1450.0f),
            FVector2D(1630.0f, 1130.0f),
            FVector2D(720.0f, 850.0f),
            FVector2D(-120.0f, 860.0f)
        };
        TArray<FVector> LakeVertices;
        TArray<int32> LakeTriangles;
        TArray<FVector> LakeNormals;
        TArray<FVector2D> LakeUVs;
        TArray<FColor> LakeColors;
        TArray<FProcMeshTangent> LakeTangents;
        LakeVertices.Add(FVector(70000.0f, 145000.0f, LakeHeightCm));
        LakeNormals.Add(FVector::UpVector);
        LakeUVs.Add(FVector2D(0.5f, 0.5f));
        LakeColors.Add(FColor::White);
        LakeTangents.Add(FProcMeshTangent(FVector::ForwardVector, false));
        for (const FVector2D& PointM : ShoreM)
        {
            LakeVertices.Add(FVector(
                PointM.X * 100.0f, PointM.Y * 100.0f, LakeHeightCm));
            LakeNormals.Add(FVector::UpVector);
            LakeUVs.Add(FVector2D(
                (PointM.X + 900.0f) / 3210.0f,
                (PointM.Y - 850.0f) / 1260.0f));
            LakeColors.Add(FColor::White);
            LakeTangents.Add(FProcMeshTangent(FVector::ForwardVector, false));
        }
        for (int32 Edge = 0; Edge < ShoreM.Num(); ++Edge)
        {
            const int32 A = Edge + 1;
            const int32 B = ((Edge + 1) % ShoreM.Num()) + 1;
            // Procedural terrain uses clockwise front faces in Unreal's
            // coordinate convention. The old (0,B,A) order pointed this
            // single-sided opaque surface down, so Lake Thun was culled when
            // viewed from the air despite having valid vertices/material.
            LakeTriangles.Append({0, A, B});
        }
        LakeSurface->CreateMeshSection(
            0, LakeVertices, LakeTriangles, LakeNormals, LakeUVs,
            LakeColors, LakeTangents, false);
        if (UMaterialInterface* AuthoredWater = LoadObject<UMaterialInterface>(
            nullptr, TEXT("/Game/Materials/M_WaterSurface.M_WaterSurface")))
        {
            UMaterialInstanceDynamic* LakeMaterial =
                UMaterialInstanceDynamic::Create(AuthoredWater, Lake);
            LakeMaterial->SetVectorParameterValue(
                TEXT("DeepWaterColor"), FLinearColor(0.004f, 0.070f, 0.105f));
            LakeMaterial->SetVectorParameterValue(
                TEXT("GrazingWaterColor"), FLinearColor(0.035f, 0.30f, 0.38f));
            LakeSurface->SetMaterial(0, LakeMaterial);
            WaterMaterialInstances.Add(LakeMaterial);
        }
        else
        {
            UMaterialInstanceDynamic* WaterMaterial =
                UMaterialInstanceDynamic::Create(ShapeMaterial, Lake);
            WaterMaterial->SetVectorParameterValue(
                TEXT("Color"), FLinearColor(0.018f, 0.19f, 0.31f, 1.0f));
            LakeSurface->SetMaterial(0, WaterMaterial);
        }

        // A narrow wet bank breaks the perfect water/terrain cut without
        // modifying the surveyed heightfield used by flight physics. The
        // inner edge hugs the water datum; the outer edge samples terrain so
        // the strip naturally disappears into steeper banks.
        UProceduralMeshComponent* Shoreline =
            NewObject<UProceduralMeshComponent>(Lake, TEXT("LakeThunShoreline"));
        Shoreline->SetupAttachment(LakeSurface);
        Shoreline->SetCollisionEnabled(ECollisionEnabled::NoCollision);
        Shoreline->SetCastShadow(false);
        Shoreline->RegisterComponent();
        TArray<FVector> ShoreVertices;
        TArray<int32> ShoreTriangles;
        TArray<FVector> ShoreNormals;
        TArray<FVector2D> ShoreUVs;
        TArray<FColor> ShoreColors;
        TArray<FProcMeshTangent> ShoreTangents;
        const FVector2D ShoreCentreM(700.0f, 1450.0f);
        constexpr float ShoreWidthM = 18.0f;
        for (int32 PointIndex = 0; PointIndex < ShoreM.Num(); ++PointIndex)
        {
            const FVector2D InnerM = ShoreM[PointIndex];
            const FVector2D Outward =
                (InnerM - ShoreCentreM).GetSafeNormal();
            const FVector2D OuterM = InnerM + Outward * ShoreWidthM;
            const float OuterGroundM = static_cast<float>(
                Parapenting::Physics::TerrainModel::HeightM(
                    OuterM.X, OuterM.Y));
            ShoreVertices.Add(FVector(
                InnerM.X * 100.0f, InnerM.Y * 100.0f,
                LakeHeightCm + 3.0f));
            ShoreVertices.Add(FVector(
                OuterM.X * 100.0f, OuterM.Y * 100.0f,
                OuterGroundM * 100.0f + 8.0f));
            ShoreNormals.Append({FVector::UpVector, FVector::UpVector});
            ShoreUVs.Append({
                FVector2D(PointIndex / static_cast<float>(ShoreM.Num()), 0.0f),
                FVector2D(PointIndex / static_cast<float>(ShoreM.Num()), 1.0f)});
            ShoreColors.Append({FColor::White, FColor::White});
            ShoreTangents.Append({
                FProcMeshTangent(FVector::ForwardVector, false),
                FProcMeshTangent(FVector::ForwardVector, false)});
            const int32 Next = (PointIndex + 1) % ShoreM.Num();
            ShoreTriangles.Append({
                PointIndex * 2, Next * 2 + 1, Next * 2,
                PointIndex * 2, PointIndex * 2 + 1, Next * 2 + 1});
        }
        Shoreline->CreateMeshSection(
            0, ShoreVertices, ShoreTriangles, ShoreNormals, ShoreUVs,
            ShoreColors, ShoreTangents, false);
        if (UMaterialInterface* Soil = LoadObject<UMaterialInterface>(
            nullptr, TEXT("/Game/Materials/MI_Soil.MI_Soil")))
        {
            Shoreline->SetMaterial(0, Soil);
        }
        else
        {
            UMaterialInstanceDynamic* WetBankMaterial =
                UMaterialInstanceDynamic::Create(ShapeMaterial, Lake);
            WetBankMaterial->SetVectorParameterValue(
                TEXT("Color"), FLinearColor(0.055f, 0.07f, 0.035f, 1.0f));
            Shoreline->SetMaterial(0, WetBankMaterial);
        }

        // The Aare and the main valley road form strong visual references
        // during the final glide into Interlaken and Lehn.
        AActor* ValleyLines = World->SpawnActor<AActor>();
        UProceduralMeshComponent* River =
            NewObject<UProceduralMeshComponent>(
                ValleyLines, TEXT("AareRiver"));
        UHierarchicalInstancedStaticMeshComponent* Road =
            NewObject<UHierarchicalInstancedStaticMeshComponent>(
                ValleyLines, TEXT("ValleyRoad"));
        ValleyLines->SetRootComponent(River);
        Road->SetupAttachment(River);
        Road->SetStaticMesh(CubeMesh);
        River->SetCollisionEnabled(ECollisionEnabled::NoCollision);
        River->SetCastShadow(false);
        Road->SetCollisionEnabled(ECollisionEnabled::NoCollision);
        Road->SetCullDistances(60000, 900000);
        River->RegisterComponent();
        Road->RegisterComponent();
        if (UMaterialInterface* AuthoredWater = LoadObject<UMaterialInterface>(
            nullptr, TEXT("/Game/Materials/M_WaterSurface.M_WaterSurface")))
        {
            UMaterialInstanceDynamic* RiverMaterial =
                UMaterialInstanceDynamic::Create(AuthoredWater, ValleyLines);
            RiverMaterial->SetVectorParameterValue(
                TEXT("DeepWaterColor"),
                FLinearColor(0.004f, 0.035f, 0.045f, 1.0f));
            RiverMaterial->SetVectorParameterValue(
                TEXT("GrazingWaterColor"),
                FLinearColor(0.012f, 0.085f, 0.095f, 1.0f));
            RiverMaterial->SetScalarParameterValue(
                TEXT("WaterRoughness"), 0.34f);
            RiverMaterial->SetScalarParameterValue(
                TEXT("WaterSpecular"), 0.32f);
            River->SetMaterial(0, RiverMaterial);
            WaterMaterialInstances.Add(RiverMaterial);
        }
        else
        {
            UMaterialInstanceDynamic* RiverMaterial =
                UMaterialInstanceDynamic::Create(ShapeMaterial, ValleyLines);
            RiverMaterial->SetVectorParameterValue(
                TEXT("Color"), FLinearColor(0.025f, 0.28f, 0.42f));
            River->SetMaterial(0, RiverMaterial);
        }
        UMaterialInstanceDynamic* RoadMaterial =
            UMaterialInstanceDynamic::Create(ShapeMaterial, ValleyLines);
        RoadMaterial->SetVectorParameterValue(
            TEXT("Color"), FLinearColor(0.12f, 0.125f, 0.12f));
        Road->SetMaterial(0, RoadMaterial);
        // Build one continuous ribbon instead of 52 scaled cubes. The old
        // segment gaps flashed as cyan runway markings from the flight camera
        // and made the river disappear whenever the view aligned with them.
        TArray<FVector> RiverVertices;
        TArray<int32> RiverTriangles;
        TArray<FVector> RiverNormals;
        TArray<FVector2D> RiverUVs;
        TArray<FColor> RiverColors;
        TArray<FProcMeshTangent> RiverTangents;
        constexpr int32 RiverPointCount = 53;
        constexpr float RiverStepM = 92.0f;
        constexpr float RiverHalfWidthM = 7.0f;
        for (int32 Point = 0; Point < RiverPointCount; ++Point)
        {
            const float X = 1500.0f + Point * RiverStepM;
            const float RiverY = 610.0f
                - 125.0f * FMath::Sin(Point * 0.21f);
            const float PreviousY = 610.0f
                - 125.0f * FMath::Sin(FMath::Max(0, Point - 1) * 0.21f);
            const float NextY = 610.0f
                - 125.0f * FMath::Sin(
                    FMath::Min(RiverPointCount - 1, Point + 1) * 0.21f);
            const FVector2D Tangent = FVector2D(
                Point == 0 || Point == RiverPointCount - 1
                    ? RiverStepM : RiverStepM * 2.0f,
                NextY - PreviousY).GetSafeNormal();
            const FVector2D Across(-Tangent.Y, Tangent.X);
            for (int32 Side = -1; Side <= 1; Side += 2)
            {
                const float VertexX = X + Across.X * RiverHalfWidthM * Side;
                const float VertexY = RiverY
                    + Across.Y * RiverHalfWidthM * Side;
                const float Ground = static_cast<float>(
                    Parapenting::Physics::TerrainModel::HeightM(
                        VertexX, VertexY));
                RiverVertices.Add(
                    FVector(VertexX, VertexY, Ground + 0.35f) * 100.0f);
                RiverNormals.Add(FVector::UpVector);
                RiverUVs.Add(FVector2D(
                    Point * RiverStepM / 100.0f,
                    Side < 0 ? 0.0f : 1.0f));
                RiverColors.Add(FColor::White);
                RiverTangents.Add(FProcMeshTangent(
                    FVector(Tangent.X, Tangent.Y, 0.0f), false));
            }
            if (Point > 0)
            {
                const int32 Previous = (Point - 1) * 2;
                const int32 Current = Point * 2;
                RiverTriangles.Append({
                    Previous, Current + 1, Current,
                    Previous, Previous + 1, Current + 1});
            }
        }
        River->CreateMeshSection(
            0, RiverVertices, RiverTriangles, RiverNormals, RiverUVs,
            RiverColors, RiverTangents, false);

        for (int32 Segment = 0; Segment < 52; ++Segment)
        {
            const float X = 1500.0f + Segment * 92.0f;
            const float RoadY = -310.0f
                - 70.0f * FMath::Sin(Segment * 0.17f + 1.4f);
            const float NextRoadY = -310.0f
                - 70.0f * FMath::Sin((Segment + 1) * 0.17f + 1.4f);
            const float RoadYaw = FMath::RadiansToDegrees(
                FMath::Atan2(NextRoadY - RoadY, 92.0f));
            const float RoadGround = static_cast<float>(
                Parapenting::Physics::TerrainModel::HeightM(X, RoadY));
            Road->AddInstance(FTransform(
                FRotator(0.0f, RoadYaw, 0.0f),
                FVector(X, RoadY, RoadGround + 0.42f) * 100.0f,
                FVector(96.0f, 5.2f, 0.18f)));
        }
    }

    if (CylinderMesh && ConeMesh && ShapeMaterial)
    {
        TSet<FString> MarkedLandings;
        for (std::size_t Index = 0;
             Index < Parapenting::Physics::RouteProfileCount(); ++Index)
        {
            const auto& Route =
                Parapenting::Physics::GetRouteProfileByIndex(Index);
            const FString LandingId = ANSI_TO_TCHAR(Route.landing.id);
            if (MarkedLandings.Contains(LandingId)) continue;
            MarkedLandings.Add(LandingId);
            const auto Position =
                Parapenting::Physics::RouteLandingLocalM(Route);
            const float Ground = static_cast<float>(
                Parapenting::Physics::TerrainModel::HeightM(
                    Position.x, Position.y));
            AStaticMeshActor* Marker = World->SpawnActor<AStaticMeshActor>(
                FVector(Position.x, Position.y, Ground + 0.18) * 100.0,
                FRotator::ZeroRotator);
            Marker->GetStaticMeshComponent()->SetStaticMesh(CylinderMesh);
            Marker->GetStaticMeshComponent()->SetWorldScale3D(
                FVector(3.8f, 3.8f, 0.025f));
            Marker->GetStaticMeshComponent()->SetCollisionEnabled(
                ECollisionEnabled::NoCollision);
            UMaterialInstanceDynamic* MarkerMaterial =
                UMaterialInstanceDynamic::Create(ShapeMaterial, Marker);
            MarkerMaterial->SetVectorParameterValue(
                TEXT("Color"),
                Route.advancedLanding
                    ? FLinearColor(0.95f, 0.55f, 0.05f)
                    : FLinearColor(0.92f, 0.92f, 0.88f));
            Marker->GetStaticMeshComponent()->SetMaterial(0, MarkerMaterial);

            // Every selectable landing gets a locally sampled surface-wind
            // cue. Offset it across the field so the pole does not cover the
            // route marker; this is presentation, not a surveyed sock position.
            const FVector2D SockPosition(
                Position.x, Position.y + 20.0);
            const float SockGround = static_cast<float>(
                Parapenting::Physics::TerrainModel::HeightM(
                    SockPosition.X, SockPosition.Y));
            AStaticMeshActor* Pole = World->SpawnActor<AStaticMeshActor>(
                FVector(SockPosition.X, SockPosition.Y, SockGround + 3.0)
                    * 100.0,
                FRotator::ZeroRotator);
            Pole->GetStaticMeshComponent()->SetStaticMesh(CylinderMesh);
            Pole->GetStaticMeshComponent()->SetWorldScale3D(
                FVector(0.06f, 0.06f, 6.0f));
            Pole->GetStaticMeshComponent()->SetCollisionEnabled(
                ECollisionEnabled::NoCollision);

            AStaticMeshActor* Windsock = World->SpawnActor<AStaticMeshActor>(
                FVector(SockPosition.X, SockPosition.Y, SockGround + 5.9)
                    * 100.0,
                FRotator(0.0, 0.0, 90.0));
            UStaticMeshComponent* SockComponent =
                Windsock->GetStaticMeshComponent();
            SockComponent->SetStaticMesh(ConeMesh);
            SockComponent->SetWorldScale3D(FVector(0.35f, 0.35f, 3.0f));
            SockComponent->SetCollisionEnabled(ECollisionEnabled::NoCollision);
            UMaterialInstanceDynamic* SockMaterial =
                UMaterialInstanceDynamic::Create(ShapeMaterial, Windsock);
            SockMaterial->SetVectorParameterValue(
                TEXT("Color"), FLinearColor(1.0f, 0.18f, 0.03f));
            SockComponent->SetMaterial(0, SockMaterial);
            WindsockComponents.Add(SockComponent);
            WindsockAnchorsCm.Add(Windsock->GetActorLocation());
            WindsockSamplePositionsM.Add(SockPosition);
        }
    }
}

void AParapentingGameMode::Tick(float DeltaSeconds)
{
    Super::Tick(DeltaSeconds);
    AParagliderPawn* Glider =
        Cast<AParagliderPawn>(GetWorld() ? GetWorld()->GetFirstPlayerController()
            ? GetWorld()->GetFirstPlayerController()->GetPawn() : nullptr
            : nullptr);
    if (!Glider) return;

    if (bVisualQACaptureRequested && !bVisualQATimeApplied)
    {
        StartVisualQACapture(*Glider);
    }
    if (bVisualQACaptureRequested && bVisualQATimeApplied
        && !bVisualQAScreenshotRequested)
    {
        VisualQAWarmupSeconds -= DeltaSeconds;
        if (VisualQAWarmupSeconds <= 0.0f)
        {
            bVisualQAScreenshotRequested = true;
            FScreenshotRequest::OnScreenshotCaptured().AddUObject(
                this, &AParapentingGameMode::SaveVisualQACapture);
            FScreenshotRequest::OnScreenshotRequestProcessed().AddUObject(
                this, &AParapentingGameMode::FinishVisualQACapture);
            FScreenshotRequest::RequestScreenshot(
                VisualQACapturePath, false, false, false, FIntRect(), true);
            UE_LOG(LogTemp, Display,
                TEXT("Parapenting Visual QA: requested %s"),
                *VisualQACapturePath);
        }
    }
    const auto Cloud = Glider->GetCloudFieldState();
    const auto& Weather = Glider->GetWeatherSnapshot();
    const float WeatherEnergy = FMath::Clamp(
        static_cast<float>((Weather.windSpeedMps + Weather.gustSpeedMps)
            / 11.0), 0.0f, 1.0f);
    const float CloudVeil = FMath::Clamp(
        static_cast<float>(Cloud.coverage * (0.35 + 0.65 * Cloud.development)),
        0.0f, 1.0f);
    if (FogComponent)
    {
        // This is a pure view of the deterministic weather snapshot: calm
        // air remains clear, while stronger/gustier presets develop a bounded
        // valley veil. It changes no atmosphere samples, forces or replays.
        // Coverage and development are the available humidity proxy.  They
        // shape distance presentation only; they are not treated as rain or
        // surface wetness because WeatherSnapshot has no precipitation state.
        FogComponent->SetFogDensity(FMath::Lerp(
            0.00008f, 0.00019f, FMath::Max(WeatherEnergy, CloudVeil)));
        FogComponent->SetFogHeightFalloff(FMath::Lerp(
            0.18f, 0.08f, WeatherEnergy));
        FogComponent->SetStartDistance(FMath::Lerp(
            26000.0f, 9000.0f, WeatherEnergy));
        FogComponent->SetFogInscatteringColor(FLinearColor::LerpUsingHSV(
            FLinearColor(0.075f, 0.095f, 0.115f),
            FLinearColor(0.080f, 0.075f, 0.070f), WeatherEnergy));
    }
    if (CloudComponent)
    {
        CloudComponent->SetLayerBottomAltitude(
            static_cast<float>(Cloud.baseAltitudeM / 1000.0));
        CloudComponent->SetLayerHeight(
            static_cast<float>(Cloud.layerThicknessM / 1000.0));
    }
    if (CloudMaterialInstance)
    {
        CloudMaterialInstance->SetScalarParameterValue(
            TEXT("Coverage"), static_cast<float>(Cloud.coverage));
        CloudMaterialInstance->SetScalarParameterValue(
            TEXT("Density"), static_cast<float>(
                0.35 + 0.65 * Cloud.development));
        CloudMaterialInstance->SetVectorParameterValue(
            TEXT("WindOffset"),
            FLinearColor(
                static_cast<float>(Cloud.driftM.x / 10000.0),
                static_cast<float>(Cloud.driftM.y / 10000.0),
                0.0f, 0.0f));
    }
    for (UMaterialInstanceDynamic* Water : WaterMaterialInstances)
    {
        if (!Water) continue;
        // Wind adds short ripples and breaks reflections.  The material has no
        // wave displacement yet, so roughness/specular are deliberately the
        // only response rather than pretending that a visual normal map is
        // physical water motion.
        Water->SetScalarParameterValue(TEXT("WaterRoughness"),
            FMath::Lerp(0.10f, 0.42f, WeatherEnergy));
        Water->SetScalarParameterValue(TEXT("WaterSpecular"),
            FMath::Lerp(0.68f, 0.28f, WeatherEnergy));
    }
    if (SunComponent)
    {
        const auto Diurnal = Glider->GetDiurnalState();
        SunComponent->SetWorldRotation(FRotator(
            static_cast<float>(-Diurnal.sunElevationDegrees),
            static_cast<float>(Diurnal.sunAzimuthDegrees - 90.0),
            0.0f));
        SunComponent->SetIntensity(static_cast<float>(
            0.12 + 7.38 * Diurnal.ambientLight));
        const FLinearColor Neutral(1.0f, 0.98f, 0.94f);
        const FLinearColor Golden(1.0f, 0.72f, 0.48f);
        SunComponent->SetLightColor(FLinearColor::LerpUsingHSV(
            Neutral, Golden,
            static_cast<float>(Diurnal.warmLight * 0.38)));
        SunComponent->CloudShadowStrength =
            static_cast<float>(
                Cloud.shadowStrength * Diurnal.ambientLight);
        SunComponent->CloudShadowOnSurfaceStrength =
            static_cast<float>(
                Cloud.shadowStrength * Diurnal.ambientLight);
        if (SkyLightComponent)
        {
            // Keep shadow fill coupled to deterministic simulation time. The
            // sky remains present near dawn, while midday gets enough diffuse
            // light to preserve forest and rock detail without flattening the
            // directional sun term.
            SkyLightComponent->SetIntensity(static_cast<float>(
                0.42 + 0.93 * Diurnal.ambientLight));
        }
    }
    for (int32 Index = 0;
         Index < WindsockComponents.Num()
         && Index < WindsockAnchorsCm.Num()
         && Index < WindsockSamplePositionsM.Num();
         ++Index)
    {
        UStaticMeshComponent* WindsockComponent = WindsockComponents[Index];
        if (!WindsockComponent) continue;
        const FVector2D SamplePosition = WindsockSamplePositionsM[Index];
        const double GroundM =
            Parapenting::Physics::TerrainModel::HeightM(
                SamplePosition.X, SamplePosition.Y);
        const auto Air = Glider->SampleAtmosphereAt(
            {SamplePosition.X, SamplePosition.Y, GroundM + 6.0});
        const auto Sock = Parapenting::Physics::EvaluateWindsockPose(
            Air.windWorldMps, Air.gustEnergyMps,
            Glider->GetSimulationTimeSeconds());
        const FVector Direction(
            Sock.directionWorld.x,
            Sock.directionWorld.y,
            Sock.directionWorld.z);
        const float LengthCm =
            static_cast<float>(300.0 * Sock.lengthScale);
        WindsockComponent->SetWorldRotation(
            FQuat::FindBetweenNormals(FVector::UpVector, Direction));
        WindsockComponent->SetWorldScale3D(FVector(
            static_cast<float>(Sock.radiusScale),
            static_cast<float>(Sock.radiusScale),
            static_cast<float>(3.0 * Sock.lengthScale)));
        WindsockComponent->SetWorldLocation(
            WindsockAnchorsCm[Index] + Direction * (LengthCm * 0.5f));
    }
}

void AParapentingGameMode::StartVisualQACapture(AParagliderPawn& Glider)
{
    bVisualQATimeApplied = true;
    if (VisualQAWeatherPreset >= 0
        && VisualQAWeatherPreset <= static_cast<int32>(
            Parapenting::Physics::WeatherPresetId::EveningDrainage))
    {
        Glider.SetVisualQAWeatherPreset(
            static_cast<Parapenting::Physics::WeatherPresetId>(
                VisualQAWeatherPreset));
    }
    Glider.SetVisualQALocalHour(VisualQALocalHour);

    FString SafeName = VisualQACaptureName;
    for (TCHAR& Character : SafeName)
    {
        if (!FChar::IsAlnum(Character) && Character != TEXT('-')
            && Character != TEXT('_'))
        {
            Character = TEXT('_');
        }
    }
    if (SafeName.IsEmpty())
        SafeName = TEXT("capture");

    const FString CaptureDirectory = FPaths::Combine(
        FPaths::ProjectSavedDir(), TEXT("VisualQA"));
    IFileManager::Get().MakeDirectory(*CaptureDirectory, true);
    VisualQACapturePath = FPaths::Combine(
        CaptureDirectory,
        FString::Printf(TEXT("%s_%05.2fh.png"),
            *SafeName, VisualQALocalHour));

    if (APlayerController* Controller = GetWorld()
            ? GetWorld()->GetFirstPlayerController() : nullptr)
    {
        Controller->SetShowMouseCursor(false);
        if (AHUD* Hud = Controller->GetHUD())
            Hud->bShowHUD = false;
    }
    UE_LOG(LogTemp, Display,
        TEXT("Parapenting Visual QA: fixed time %.2f, warmup %.1fs"),
        VisualQALocalHour, VisualQAWarmupSeconds);
}

void AParapentingGameMode::FinishVisualQACapture()
{
    FScreenshotRequest::OnScreenshotCaptured().RemoveAll(this);
    FScreenshotRequest::OnScreenshotRequestProcessed().RemoveAll(this);
    const bool bCaptureWritten =
        IFileManager::Get().FileSize(*VisualQACapturePath) > 0;
    if (bCaptureWritten)
    {
        UE_LOG(LogTemp, Display,
            TEXT("Parapenting Visual QA: captured %s"),
            *VisualQACapturePath);
    }
    else
    {
        UE_LOG(LogTemp, Error,
            TEXT("Parapenting Visual QA: FAILED to capture %s"),
            *VisualQACapturePath);
    }
    FPlatformMisc::RequestExitWithStatus(false, bCaptureWritten ? 0 : 2);
}

void AParapentingGameMode::SaveVisualQACapture(
    int32 Width, int32 Height, const TArray<FColor>& Colors)
{
    TArray64<uint8> CompressedPng;
    FImageUtils::PNGCompressImageArray(
        Width, Height, MakeArrayView(Colors), CompressedPng);
    if (!FFileHelper::SaveArrayToFile(CompressedPng, *VisualQACapturePath))
    {
        UE_LOG(LogTemp, Error,
            TEXT("Parapenting Visual QA: could not write %s"),
            *VisualQACapturePath);
    }
}
