"""Create the checked-in Level 1 material library in Unreal Editor.

Run from the project root with:
  UnrealEditor-Cmd Parapenting.uproject \
    -run=pythonscript -script=Tools/Visual/create_level1_materials.py \
    -unattended -nop4

The script is intentionally idempotent. It updates the small set of authored
material assets instead of relying on opaque manual editor work.
"""

import os

import unreal


ROOT = "/Game/Materials"
TEXTURE_ROOT = f"{ROOT}/Textures"
# Keep the editable, reviewable source image in the repository. The imported
# UAsset is intentionally generated by this script, just like the materials.
CANOPY_RIPSTOP_SOURCE = os.path.join(
    unreal.Paths.project_dir(),
    "Content/ArtSource/Canopy/T_CanopyRipstop_Albedo_Source_v2.png",
)
CANOPY_RIPSTOP_ASSET = f"{TEXTURE_ROOT}/T_CanopyRipstop_Albedo"
CANOPY_RIPSTOP_NORMAL_SOURCE = os.path.join(
    unreal.Paths.project_dir(),
    "Content/ArtSource/Canopy/T_CanopyRipstop_Normal_Source_v1.png",
)
CANOPY_RIPSTOP_NORMAL_ASSET = f"{TEXTURE_ROOT}/T_CanopyRipstop_Normal"


def load_or_create(name, asset_class, factory):
    path = f"{ROOT}/{name}"
    if unreal.EditorAssetLibrary.does_asset_exist(path):
        return unreal.EditorAssetLibrary.load_asset(path), False
    return (
        unreal.AssetToolsHelpers.get_asset_tools().create_asset(
            name, ROOT, asset_class, factory
        ),
        True,
    )


def import_canopy_ripstop():
    """Import the project-owned ripstop source when the material is rebuilt.

    Keeping import here means a clean clone can make the same cooked texture
    without a manual Content Browser operation. Existing imports are retained
    so routine material rebuilds do not replace user-tuned texture settings.
    """
    if unreal.EditorAssetLibrary.does_asset_exist(CANOPY_RIPSTOP_ASSET):
        return unreal.EditorAssetLibrary.load_asset(CANOPY_RIPSTOP_ASSET)
    if not unreal.Paths.file_exists(CANOPY_RIPSTOP_SOURCE):
        raise RuntimeError(
            f"Canopy ripstop source is missing: {CANOPY_RIPSTOP_SOURCE}"
        )
    unreal.EditorAssetLibrary.make_directory(TEXTURE_ROOT)
    task = unreal.AssetImportTask()
    task.set_editor_property("filename", CANOPY_RIPSTOP_SOURCE)
    task.set_editor_property("destination_path", TEXTURE_ROOT)
    task.set_editor_property("destination_name", "T_CanopyRipstop_Albedo")
    task.set_editor_property("automated", True)
    task.set_editor_property("replace_existing", False)
    task.set_editor_property("save", True)
    unreal.AssetToolsHelpers.get_asset_tools().import_asset_tasks([task])
    texture = unreal.EditorAssetLibrary.load_asset(CANOPY_RIPSTOP_ASSET)
    if not texture:
        raise RuntimeError("Could not import the canopy ripstop texture")
    texture.set_editor_property("srgb", True)
    unreal.EditorAssetLibrary.save_loaded_asset(texture, False)
    return texture


def import_canopy_ripstop_normal():
    """Import the generated shallow weave normal with correct texture flags."""
    if unreal.EditorAssetLibrary.does_asset_exist(CANOPY_RIPSTOP_NORMAL_ASSET):
        return unreal.EditorAssetLibrary.load_asset(CANOPY_RIPSTOP_NORMAL_ASSET)
    if not unreal.Paths.file_exists(CANOPY_RIPSTOP_NORMAL_SOURCE):
        raise RuntimeError(
            f"Canopy ripstop normal source is missing: {CANOPY_RIPSTOP_NORMAL_SOURCE}"
        )
    task = unreal.AssetImportTask()
    task.set_editor_property("filename", CANOPY_RIPSTOP_NORMAL_SOURCE)
    task.set_editor_property("destination_path", TEXTURE_ROOT)
    task.set_editor_property("destination_name", "T_CanopyRipstop_Normal")
    task.set_editor_property("automated", True)
    task.set_editor_property("replace_existing", False)
    task.set_editor_property("save", True)
    unreal.AssetToolsHelpers.get_asset_tools().import_asset_tasks([task])
    texture = unreal.EditorAssetLibrary.load_asset(CANOPY_RIPSTOP_NORMAL_ASSET)
    if not texture:
        raise RuntimeError("Could not import canopy ripstop normal")
    texture.set_editor_property("srgb", False)
    texture.set_editor_property(
        "compression_settings", unreal.TextureCompressionSettings.TC_NORMALMAP
    )
    unreal.EditorAssetLibrary.save_loaded_asset(texture, False)
    return texture


def scalar(material, name, value, x, y):
    node = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionScalarParameter, x, y
    )
    node.set_editor_property("parameter_name", name)
    node.set_editor_property("default_value", value)
    return node


def vector(material, name, value, x, y):
    node = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionVectorParameter, x, y
    )
    node.set_editor_property("parameter_name", name)
    node.set_editor_property("default_value", value)
    return node


def connect(node, output, material, prop):
    unreal.MaterialEditingLibrary.connect_material_property(node, output, prop)


def make_vertex_lit():
    material, created = load_or_create(
        "M_VertexLit", unreal.Material, unreal.MaterialFactoryNew()
    )
    if not created:
        return material
    material.set_editor_property("two_sided", True)
    material.set_editor_property("blend_mode", unreal.BlendMode.BLEND_OPAQUE)

    color = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionVertexColor, -420, -80
    )
    roughness = scalar(material, "Roughness", 0.92, -420, 100)
    metallic = scalar(material, "Metallic", 0.0, -420, 180)
    connect(color, "RGB", material, unreal.MaterialProperty.MP_BASE_COLOR)
    connect(roughness, "", material, unreal.MaterialProperty.MP_ROUGHNESS)
    connect(metallic, "", material, unreal.MaterialProperty.MP_METALLIC)
    unreal.MaterialEditingLibrary.recompile_material(material)
    unreal.EditorAssetLibrary.save_loaded_asset(material, False)
    return material


def make_air_motes():
    """Tiny unlit, translucent wind tracers for the camera-local mote field.

    Opacity is carried by the deterministic procedural mesh's vertex alpha;
    this keeps the VFX system data-only and avoids an independently simulated
    particle behaviour that could contradict the weather model.
    """
    material, created = load_or_create(
        "M_AirMotes", unreal.Material, unreal.MaterialFactoryNew()
    )
    if not created:
        return material
    material.set_editor_property("two_sided", True)
    material.set_editor_property(
        "blend_mode", unreal.BlendMode.BLEND_ADDITIVE
    )
    material.set_editor_property(
        "shading_model", unreal.MaterialShadingModel.MSM_UNLIT
    )
    color = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionVertexColor, -360, -40
    )
    uv = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionTextureCoordinate, -360, 160
    )
    centre = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionConstant2Vector, -170, 210
    )
    centre.set_editor_property("r", 0.5)
    centre.set_editor_property("g", 0.5)
    disc = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionSphereMask, 30, 160
    )
    disc.set_editor_property("attenuation_radius", 0.46)
    disc.set_editor_property("hardness_percent", 82.0)
    unreal.MaterialEditingLibrary.connect_material_expressions(uv, "", disc, "A")
    unreal.MaterialEditingLibrary.connect_material_expressions(
        centre, "", disc, "B"
    )
    emission = scalar(material, "MoteEmission", 1.15, -160, -100)
    emissive = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionMultiply, 50, -40
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        color, "RGB", emissive, "A"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        emission, "", emissive, "B"
    )
    masked_emissive = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionMultiply, 250, -40
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        emissive, "", masked_emissive, "A"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        disc, "", masked_emissive, "B"
    )
    opacity_scale = scalar(material, "MoteOpacity", 1.0, -160, 60)
    opacity = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionMultiply, 50, 80
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        color, "A", opacity, "A"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        opacity_scale, "", opacity, "B"
    )
    masked_opacity = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionMultiply, 250, 80
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        opacity, "", masked_opacity, "A"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        disc, "", masked_opacity, "B"
    )
    connect(
        masked_emissive, "", material,
        unreal.MaterialProperty.MP_EMISSIVE_COLOR
    )
    connect(masked_opacity, "", material, unreal.MaterialProperty.MP_OPACITY)
    unreal.MaterialEditingLibrary.recompile_material(material)
    unreal.EditorAssetLibrary.save_loaded_asset(material, False)
    return material


def make_canopy_fabric():
    """Two-sided transmitted-light fabric for the procedural canopy.

    The weave is evaluated in the canopy's existing UVs, not world space: the
    field stays locked to the moving/deforming procedural skin and never reads
    as dirt sliding across the wing.
    """
    material, created = load_or_create(
        "M_CanopyFabric", unreal.Material, unreal.MaterialFactoryNew()
    )
    if not created:
        return material
    material.set_editor_property("two_sided", True)
    material.set_editor_property("blend_mode", unreal.BlendMode.BLEND_OPAQUE)
    material.set_editor_property(
        "shading_model",
        unreal.MaterialShadingModel.MSM_TWO_SIDED_FOLIAGE,
    )
    ripstop_texture = import_canopy_ripstop()
    ripstop_normal = import_canopy_ripstop_normal()
    color = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionVertexColor, -520, -80
    )
    transmission_tint = vector(
        material, "TransmissionTint",
        unreal.LinearColor(0.72, 0.34, 0.18, 1.0), -520, 100
    )
    transmitted_color = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionMultiply, -260, 80
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        color, "RGB", transmitted_color, "A"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        transmission_tint, "RGB", transmitted_color, "B"
    )
    two_sided_sign = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionTwoSidedSign, -520, 260
    )
    inverse_sign = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionOneMinus, -320, 300
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        two_sided_sign, "", inverse_sign, ""
    )
    half = scalar(material, "TwoSidedMaskScale", 0.5, -320, 380)
    underside_mask = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionMultiply, -120, 300
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        inverse_sign, "", underside_mask, "A"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        half, "", underside_mask, "B"
    )
    neutral = scalar(material, "FrontAlbedoScale", 1.0, -120, 400)
    underside_lift = scalar(material, "UndersideAlbedoScale", 1.55, -120, 480)
    side_scale = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionLinearInterpolate, 100, 320
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        neutral, "", side_scale, "A"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        underside_lift, "", side_scale, "B"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        underside_mask, "", side_scale, "Alpha"
    )
    sided_color = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionMultiply, 320, 40
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        color, "RGB", sided_color, "A"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        side_scale, "", sided_color, "B"
    )
    texture_coordinate = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionTextureCoordinate, -520, 600
    )
    weave_broad = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionNoise, -280, 560
    )
    weave_broad.set_editor_property("scale", 16.0)
    weave_broad.set_editor_property("quality", 1)
    weave_broad.set_editor_property("levels", 1)
    weave_broad.set_editor_property("output_min", 0.94)
    weave_broad.set_editor_property("output_max", 1.035)
    unreal.MaterialEditingLibrary.connect_material_expressions(
        texture_coordinate, "", weave_broad, "Position"
    )
    weave_fine = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionNoise, -280, 700
    )
    weave_fine.set_editor_property("scale", 72.0)
    weave_fine.set_editor_property("quality", 1)
    weave_fine.set_editor_property("levels", 1)
    weave_fine.set_editor_property("output_min", 0.975)
    weave_fine.set_editor_property("output_max", 1.025)
    unreal.MaterialEditingLibrary.connect_material_expressions(
        texture_coordinate, "", weave_fine, "Position"
    )
    weave = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionMultiply, -40, 620
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        weave_broad, "", weave, "A"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        weave_fine, "", weave, "B"
    )
    woven_color = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionMultiply, 550, 40
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        sided_color, "", woven_color, "A"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        weave, "", woven_color, "B"
    )
    # Procedural mesh vertex colours are the detailed panel signal, but Metal
    # can occasionally deliver a neutral stream for a dynamically-updated
    # section.  Keep the selected wing colour as an explicit material
    # parameter so the canopy remains unmistakably coloured in that case;
    # vertex colours still supply the panel variation beneath the tint.
    presentation_tint = vector(
        material, "CanopyPresentationTint",
        unreal.LinearColor(0.92, 0.16, 0.035, 1.0), 550, 180
    )
    tint_override = scalar(material, "CanopyTintOverride", 0.78, 550, 260)
    presented_color = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionLinearInterpolate, 780, 40
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        woven_color, "", presented_color, "A"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        presentation_tint, "RGB", presented_color, "B"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        tint_override, "", presented_color, "Alpha"
    )
    # The physical ripstop grid is a texture rather than procedural noise: it
    # retains the small reinforcement-square cadence at close range while the
    # existing vertex colour still owns panel layout and runtime colourways.
    ripstop_uv = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionTextureCoordinate, 550, -180
    )
    # UV U runs chordwise (~3 m) and V runs spanwise (~10 m); separate tiling
    # preserves approximately square reinforcement cells on the real wing.
    ripstop_uv.set_editor_property("u_tiling", 42.0)
    ripstop_uv.set_editor_property("v_tiling", 126.0)
    ripstop_sample = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionTextureSample, 780, -180
    )
    ripstop_sample.set_editor_property("texture", ripstop_texture)
    unreal.MaterialEditingLibrary.connect_material_expressions(
        ripstop_uv, "", ripstop_sample, "UVs"
    )
    normal_sample = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionTextureSample, 780, -340
    )
    normal_sample.set_editor_property("texture", ripstop_normal)
    normal_sample.set_editor_property(
        "sampler_type", unreal.MaterialSamplerType.SAMPLERTYPE_NORMAL
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        ripstop_uv, "", normal_sample, "UVs"
    )
    ripstop_strength = scalar(material, "RipstopTextureStrength", 0.34, 780, -80)
    neutral_ripstop = vector(
        material, "NeutralRipstop", unreal.LinearColor(1.0, 1.0, 1.0, 1.0),
        780, 0
    )
    tuned_ripstop = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionLinearInterpolate, 1010, -160
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        neutral_ripstop, "RGB", tuned_ripstop, "A"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        ripstop_sample, "RGB", tuned_ripstop, "B"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        ripstop_strength, "", tuned_ripstop, "Alpha"
    )
    textured_color = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionMultiply, 1240, 40
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        presented_color, "", textured_color, "A"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        tuned_ripstop, "", textured_color, "B"
    )
    roughness = scalar(material, "FabricRoughness", 0.68, 100, 440)
    woven_roughness = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionMultiply, 320, 440
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        roughness, "", woven_roughness, "A"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        weave_fine, "", woven_roughness, "B"
    )
    # Two-sided foliage receives transmitted light, but the underside can
    # still collapse to near-black under an overcast sky or when the sun is
    # behind the camera. A restrained sky-fill keeps the coloured fabric
    # legible without making it an unlit emissive wing.
    underside_fill = scalar(material, "UndersideSkyFill", 0.16, 100, 560)
    underside_emissive_mask = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionMultiply, 100, 660
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        underside_mask, "", underside_emissive_mask, "A"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        underside_fill, "", underside_emissive_mask, "B"
    )
    underside_emissive = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionMultiply, 350, 620
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        transmitted_color, "", underside_emissive, "A"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        underside_emissive_mask, "", underside_emissive, "B"
    )
    connect(textured_color, "", material, unreal.MaterialProperty.MP_BASE_COLOR)
    connect(
        transmitted_color, "", material,
        unreal.MaterialProperty.MP_SUBSURFACE_COLOR
    )
    connect(woven_roughness, "", material, unreal.MaterialProperty.MP_ROUGHNESS)
    connect(normal_sample, "RGB", material, unreal.MaterialProperty.MP_NORMAL)
    connect(underside_emissive, "", material, unreal.MaterialProperty.MP_EMISSIVE_COLOR)
    unreal.MaterialEditingLibrary.recompile_material(material)
    unreal.EditorAssetLibrary.save_loaded_asset(material, False)
    return material


def make_water_surface():
    """Opaque alpine water with stable, low-contrast world-space breakup.

    The water meshes do not carry authored UVs.  Absolute world position keeps
    the variation continuous across the surveyed lake cells and the Aare
    ribbon, while the dynamic instance still supplies the weather-driven
    roughness and specular response at runtime.
    """
    material, created = load_or_create(
        "M_WaterSurface", unreal.Material, unreal.MaterialFactoryNew()
    )
    if not created:
        return material
    material.set_editor_property("two_sided", False)
    material.set_editor_property("blend_mode", unreal.BlendMode.BLEND_OPAQUE)
    deep = vector(
        material, "DeepWaterColor",
        unreal.LinearColor(0.006, 0.055, 0.075, 1.0), -520, -80
    )
    grazing = vector(
        material, "GrazingWaterColor",
        unreal.LinearColor(0.025, 0.20, 0.24, 1.0), -520, 20
    )
    fresnel = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionFresnel, -300, 100
    )
    water_color = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionLinearInterpolate, -40, -40
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        deep, "RGB", water_color, "A"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        grazing, "RGB", water_color, "B"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        fresnel, "", water_color, "Alpha"
    )
    world_position = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionWorldPosition, -520, 180
    )
    broad_breakup = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionNoise, -290, 180
    )
    # Position is centimetres: this is a subtle 30-180 m tonal variation, not
    # a visible procedural pattern from the cockpit.
    broad_breakup.set_editor_property("scale", 0.00045)
    broad_breakup.set_editor_property("quality", 1)
    broad_breakup.set_editor_property("levels", 2)
    broad_breakup.set_editor_property("output_min", 0.82)
    broad_breakup.set_editor_property("output_max", 1.04)
    broad_breakup.set_editor_property("level_scale", 2.3)
    unreal.MaterialEditingLibrary.connect_material_expressions(
        world_position, "", broad_breakup, "Position"
    )
    fine_breakup = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionNoise, -290, 290
    )
    # Five-to-twenty metre breakup gives a water surface some body without
    # pretending the source heightfield contains wave geometry.
    fine_breakup.set_editor_property("scale", 0.003)
    fine_breakup.set_editor_property("quality", 1)
    fine_breakup.set_editor_property("levels", 1)
    fine_breakup.set_editor_property("output_min", 0.90)
    fine_breakup.set_editor_property("output_max", 1.07)
    unreal.MaterialEditingLibrary.connect_material_expressions(
        world_position, "", fine_breakup, "Position"
    )
    # A second, UV-panned ripple field provides visible but restrained motion.
    # Lake and river meshes both carry continuous UVs, so it moves as one
    # surface rather than making the individual surveyed lake cells shimmer.
    water_uv = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionTextureCoordinate, -520, 410
    )
    ripple_pan = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionPanner, -300, 410
    )
    ripple_pan.set_editor_property("speed_x", 0.009)
    ripple_pan.set_editor_property("speed_y", -0.014)
    unreal.MaterialEditingLibrary.connect_material_expressions(
        water_uv, "", ripple_pan, "Coordinate"
    )
    moving_ripples = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionNoise, -70, 390
    )
    moving_ripples.set_editor_property("scale", 26.0)
    moving_ripples.set_editor_property("quality", 1)
    moving_ripples.set_editor_property("levels", 1)
    moving_ripples.set_editor_property("output_min", 0.88)
    moving_ripples.set_editor_property("output_max", 1.10)
    unreal.MaterialEditingLibrary.connect_material_expressions(
        ripple_pan, "", moving_ripples, "Position"
    )
    ripple_strength = scalar(material, "WindRippleStrength", 0.38, -70, 500)
    neutral_ripple = scalar(material, "NeutralRipple", 1.0, -70, 580)
    weather_ripple = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionLinearInterpolate, 160, 400
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        neutral_ripple, "", weather_ripple, "A"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        moving_ripples, "", weather_ripple, "B"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        ripple_strength, "", weather_ripple, "Alpha"
    )
    breakup = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionMultiply, -70, 220
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        broad_breakup, "", breakup, "A"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        fine_breakup, "", breakup, "B"
    )
    ripple_breakup = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionMultiply, 160, 300
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        breakup, "", ripple_breakup, "A"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        weather_ripple, "", ripple_breakup, "B"
    )
    color_breakup = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionMultiply, 180, -40
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        water_color, "", color_breakup, "A"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        ripple_breakup, "", color_breakup, "B"
    )
    roughness = scalar(material, "WaterRoughness", 0.19, -40, 140)
    roughness_breakup = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionMultiply, 180, 120
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        roughness, "", roughness_breakup, "A"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        weather_ripple, "", roughness_breakup, "B"
    )
    specular = scalar(material, "WaterSpecular", 0.50, -40, 220)
    reflection_strength = scalar(material, "ReflectionStrength", 0.42, -40, 300)
    restrained_specular = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionMultiply, 180, 220
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        specular, "", restrained_specular, "A"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        reflection_strength, "", restrained_specular, "B"
    )
    connect(color_breakup, "", material, unreal.MaterialProperty.MP_BASE_COLOR)
    connect(roughness_breakup, "", material, unreal.MaterialProperty.MP_ROUGHNESS)
    connect(restrained_specular, "", material, unreal.MaterialProperty.MP_SPECULAR)
    unreal.MaterialEditingLibrary.recompile_material(material)
    unreal.EditorAssetLibrary.save_loaded_asset(material, False)
    return material


def make_terrain_lit():
    """Terrain-only vertex material with stable world-space macro variation.

    The canopy intentionally stays on M_VertexLit: world-position noise would
    crawl across a moving wing and make the fabric look dirty. Terrain is
    stationary, so low-frequency absolute-world noise breaks up large uniform
    procedural triangles without needing UVs or texture assets.
    """
    material, created = load_or_create(
        "M_TerrainLit", unreal.Material, unreal.MaterialFactoryNew()
    )
    if not created:
        return material
    material.set_editor_property("two_sided", False)
    material.set_editor_property("blend_mode", unreal.BlendMode.BLEND_OPAQUE)

    color = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionVertexColor, -760, -100
    )
    world_position = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionWorldPosition, -760, 80
    )
    macro_noise = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionNoise, -500, 80
    )
    # World position is centimetres. This yields broad features on roughly
    # 80-250 m scales; two levels avoid obvious repetition at flight distance.
    macro_noise.set_editor_property("scale", 0.00012)
    macro_noise.set_editor_property("quality", 1)
    macro_noise.set_editor_property("levels", 2)
    macro_noise.set_editor_property("output_min", 0.84)
    macro_noise.set_editor_property("output_max", 1.08)
    macro_noise.set_editor_property("level_scale", 3.0)
    unreal.MaterialEditingLibrary.connect_material_expressions(
        world_position, "", macro_noise, "Position"
    )

    pixel_depth = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionPixelDepth, -500, 260
    )
    fade_start = scalar(
        material, "MacroFadeStartCm", 250000.0, -500, 340
    )
    fade_range = scalar(
        material, "MacroFadeRangeCm", 200000.0, -500, 420
    )
    depth_after_start = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionSubtract, -260, 280
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        pixel_depth, "", depth_after_start, "A"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        fade_start, "", depth_after_start, "B"
    )
    normalized_depth = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionDivide, -60, 280
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        depth_after_start, "", normalized_depth, "A"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        fade_range, "", normalized_depth, "B"
    )
    fade = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionSaturate, 140, 280
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        normalized_depth, "", fade, ""
    )
    neutral_macro = scalar(material, "NeutralMacro", 1.0, -60, 160)
    distance_macro = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionLinearInterpolate, 340, 80
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        macro_noise, "", distance_macro, "A"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        neutral_macro, "", distance_macro, "B"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        fade, "", distance_macro, "Alpha"
    )

    # Projection-free cliff breakup. A 3D field has no cliff UV stretching or
    # visible planar seams, and the slope mask keeps it off fields/meadows.
    rock_noise = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionNoise, -500, 540
    )
    rock_noise.set_editor_property("scale", 0.0012)
    rock_noise.set_editor_property("quality", 1)
    rock_noise.set_editor_property("levels", 1)
    rock_noise.set_editor_property("output_min", 0.88)
    rock_noise.set_editor_property("output_max", 1.12)
    unreal.MaterialEditingLibrary.connect_material_expressions(
        world_position, "", rock_noise, "Position"
    )
    pixel_normal = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionPixelNormalWS, -500, 660
    )
    normal_z = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionComponentMask, -300, 660
    )
    normal_z.set_editor_property("r", False)
    normal_z.set_editor_property("g", False)
    normal_z.set_editor_property("b", True)
    normal_z.set_editor_property("a", False)
    unreal.MaterialEditingLibrary.connect_material_expressions(
        pixel_normal, "", normal_z, ""
    )
    inverse_up = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionOneMinus, -100, 660
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        normal_z, "", inverse_up, ""
    )
    slope_gain = scalar(material, "RockSlopeGain", 2.4, -100, 760)
    amplified_slope = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionMultiply, 100, 660
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        inverse_up, "", amplified_slope, "A"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        slope_gain, "", amplified_slope, "B"
    )
    slope_mask = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionSaturate, 300, 660
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        amplified_slope, "", slope_mask, ""
    )
    distance_rock = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionLinearInterpolate, 340, 500
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        rock_noise, "", distance_rock, "A"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        neutral_macro, "", distance_rock, "B"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        fade, "", distance_rock, "Alpha"
    )
    slope_rock = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionLinearInterpolate, 560, 480
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        neutral_macro, "", slope_rock, "A"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        distance_rock, "", slope_rock, "B"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        slope_mask, "", slope_rock, "Alpha"
    )
    combined_variation = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionMultiply, 580, 100
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        distance_macro, "", combined_variation, "A"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        slope_rock, "", combined_variation, "B"
    )

    # Contact-scale albedo breakup for approach and flare. It is deliberately
    # texture-free and fades before it can shimmer at flight altitude. Snow
    # stays clean because its vertex-alpha coverage suppresses this layer.
    near_noise = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionNoise, 360, 1040
    )
    near_noise.set_editor_property("scale", 0.008)
    near_noise.set_editor_property("quality", 1)
    near_noise.set_editor_property("levels", 1)
    near_noise.set_editor_property("output_min", 0.94)
    near_noise.set_editor_property("output_max", 1.06)
    unreal.MaterialEditingLibrary.connect_material_expressions(
        world_position, "", near_noise, "Position"
    )
    near_fade_start = scalar(
        material, "NearFadeStartCm", 35000.0, 360, 1140
    )
    near_fade_range = scalar(
        material, "NearFadeRangeCm", 45000.0, 360, 1220
    )
    near_depth_after_start = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionSubtract, 580, 1080
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        pixel_depth, "", near_depth_after_start, "A"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        near_fade_start, "", near_depth_after_start, "B"
    )
    normalized_near_depth = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionDivide, 780, 1080
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        near_depth_after_start, "", normalized_near_depth, "A"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        near_fade_range, "", normalized_near_depth, "B"
    )
    near_fade = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionSaturate, 980, 1080
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        normalized_near_depth, "", near_fade, ""
    )
    distance_near = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionLinearInterpolate, 1180, 1020
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        near_noise, "", distance_near, "A"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        neutral_macro, "", distance_near, "B"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        near_fade, "", distance_near, "Alpha"
    )
    snow_clean_near = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionLinearInterpolate, 1380, 1020
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        distance_near, "", snow_clean_near, "A"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        neutral_macro, "", snow_clean_near, "B"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        color, "A", snow_clean_near, "Alpha"
    )
    final_variation = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionMultiply, 800, 100
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        combined_variation, "", final_variation, "A"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        snow_clean_near, "", final_variation, "B"
    )

    # Preserve surveyed vertex variation while establishing an unmistakable
    # summer-vegetation mass. This also prevents atmospheric blue fill from
    # neutralising the low-saturation 8-bit terrain palette at flight range.
    vegetation_tint = vector(
        material, "VegetationTint",
        unreal.LinearColor(0.035, 0.18, 0.02, 1.0), 800, -220
    )
    vegetation_amount = scalar(
        material, "VegetationTintAmount", 0.22, 800, -140
    )
    tinted_color = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionLinearInterpolate, 1020, -180
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        color, "RGB", tinted_color, "A"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        vegetation_tint, "RGB", tinted_color, "B"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        vegetation_amount, "", tinted_color, "Alpha"
    )

    macro_color = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionMultiply, 1020, -80
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        tinted_color, "", macro_color, "A"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        final_variation, "", macro_color, "B"
    )

    roughness = scalar(material, "Roughness", 0.92, 560, 780)
    rock_roughness = scalar(material, "RockRoughness", 0.98, 560, 860)
    slope_roughness = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionLinearInterpolate, 800, 760
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        roughness, "", slope_roughness, "A"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        rock_roughness, "", slope_roughness, "B"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        slope_mask, "", slope_roughness, "Alpha"
    )
    # Terrain vertex alpha carries the exact snow coverage computed alongside
    # the terrain palette. This avoids a second, drifting snow-line formula in
    # the shader and lets snow retain a distinct broad specular response.
    snow_roughness = scalar(material, "SnowRoughness", 0.78, 800, 900)
    surface_roughness = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionLinearInterpolate, 1020, 760
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        slope_roughness, "", surface_roughness, "A"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        snow_roughness, "", surface_roughness, "B"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        color, "A", surface_roughness, "Alpha"
    )
    metallic = scalar(material, "Metallic", 0.0, -300, 300)
    connect(macro_color, "", material, unreal.MaterialProperty.MP_BASE_COLOR)
    connect(
        surface_roughness, "", material, unreal.MaterialProperty.MP_ROUGHNESS
    )
    connect(metallic, "", material, unreal.MaterialProperty.MP_METALLIC)
    unreal.MaterialEditingLibrary.recompile_material(material)
    unreal.EditorAssetLibrary.save_loaded_asset(material, False)
    return material


def make_error_material():
    material, created = load_or_create(
        "M_VisualError", unreal.Material, unreal.MaterialFactoryNew()
    )
    if not created:
        return material
    material.set_editor_property("two_sided", True)
    magenta = vector(
        material, "ErrorColor", unreal.LinearColor(1.0, 0.0, 0.72, 1.0),
        -420, -80
    )
    roughness = scalar(material, "Roughness", 0.35, -420, 100)
    connect(magenta, "RGB", material, unreal.MaterialProperty.MP_BASE_COLOR)
    connect(magenta, "RGB", material, unreal.MaterialProperty.MP_EMISSIVE_COLOR)
    connect(roughness, "", material, unreal.MaterialProperty.MP_ROUGHNESS)
    unreal.MaterialEditingLibrary.recompile_material(material)
    unreal.EditorAssetLibrary.save_loaded_asset(material, False)
    return material


def make_surface_master():
    material, created = load_or_create(
        "M_SurfaceMaster", unreal.Material, unreal.MaterialFactoryNew()
    )
    if not created:
        return material
    material.set_editor_property("two_sided", False)

    base = vector(
        material, "BaseColor", unreal.LinearColor(0.18, 0.20, 0.16, 1.0),
        -700, -180
    )
    tint = vector(
        material, "MacroTint", unreal.LinearColor(0.88, 0.94, 0.84, 1.0),
        -700, -80
    )
    multiply = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionMultiply, -380, -140
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        base, "RGB", multiply, "A"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        tint, "RGB", multiply, "B"
    )

    roughness = scalar(material, "Roughness", 0.82, -700, 80)
    wetness = scalar(material, "Wetness", 0.0, -700, 160)
    wet_scale = scalar(material, "WetRoughnessReduction", 0.55, -700, 240)
    wet_multiply = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionMultiply, -420, 150
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        wetness, "", wet_multiply, "A"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        wet_scale, "", wet_multiply, "B"
    )
    one_minus = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionOneMinus, -220, 150
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        wet_multiply, "", one_minus, ""
    )
    final_roughness = unreal.MaterialEditingLibrary.create_material_expression(
        material, unreal.MaterialExpressionMultiply, 0, 100
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        roughness, "", final_roughness, "A"
    )
    unreal.MaterialEditingLibrary.connect_material_expressions(
        one_minus, "", final_roughness, "B"
    )

    metallic = scalar(material, "Metallic", 0.0, -700, 340)
    specular = scalar(material, "Specular", 0.5, -700, 420)
    # These parameters establish the shared contract for the later terrain and
    # fabric shaders. They are deliberately inert until those levels supply
    # textures/geometry; having named defaults prevents each asset family from
    # inventing incompatible units.
    scalar(material, "DetailNormalStrength", 1.0, -700, 520)
    scalar(material, "WorldTextureScaleM", 1.0, -700, 600)
    scalar(material, "SnowAmount", 0.0, -700, 680)
    scalar(material, "WindResponse", 0.0, -700, 760)
    scalar(material, "DebugOverride", 0.0, -700, 840)

    connect(multiply, "", material, unreal.MaterialProperty.MP_BASE_COLOR)
    connect(
        final_roughness, "", material, unreal.MaterialProperty.MP_ROUGHNESS
    )
    connect(metallic, "", material, unreal.MaterialProperty.MP_METALLIC)
    connect(specular, "", material, unreal.MaterialProperty.MP_SPECULAR)
    unreal.MaterialEditingLibrary.recompile_material(material)
    unreal.EditorAssetLibrary.save_loaded_asset(material, False)
    return material


SWATCHES = {
    "MI_Grass": ((0.09, 0.24, 0.045, 1.0), 0.92, 0.0),
    "MI_Soil": ((0.16, 0.085, 0.035, 1.0), 0.96, 0.0),
    "MI_Limestone": ((0.34, 0.33, 0.30, 1.0), 0.88, 0.0),
    "MI_Snow": ((0.78, 0.82, 0.86, 1.0), 0.72, 0.0),
    "MI_Water": ((0.018, 0.12, 0.16, 1.0), 0.08, 0.0),
    "MI_RipstopNylon": ((0.86, 0.12, 0.035, 1.0), 0.58, 0.0),
    "MI_Webbing": ((0.035, 0.038, 0.042, 1.0), 0.9, 0.0),
    "MI_Metal": ((0.32, 0.34, 0.36, 1.0), 0.3, 1.0),
    "MI_Clothing": ((0.055, 0.075, 0.10, 1.0), 0.86, 0.0),
}


def make_swatches(parent):
    factory = unreal.MaterialInstanceConstantFactoryNew()
    for name, (color, roughness, metallic) in SWATCHES.items():
        instance, _ = load_or_create(
            name, unreal.MaterialInstanceConstant, factory
        )
        instance.set_editor_property("parent", parent)
        unreal.MaterialEditingLibrary.set_material_instance_vector_parameter_value(
            instance, "BaseColor", unreal.LinearColor(*color)
        )
        unreal.MaterialEditingLibrary.set_material_instance_vector_parameter_value(
            instance, "MacroTint", unreal.LinearColor(1.0, 1.0, 1.0, 1.0)
        )
        unreal.MaterialEditingLibrary.set_material_instance_scalar_parameter_value(
            instance, "Roughness", roughness
        )
        unreal.MaterialEditingLibrary.set_material_instance_scalar_parameter_value(
            instance, "Metallic", metallic
        )
        unreal.EditorAssetLibrary.save_loaded_asset(instance, False)


def build_material_library():
    unreal.EditorAssetLibrary.make_directory(ROOT)
    make_vertex_lit()
    make_air_motes()
    make_canopy_fabric()
    make_water_surface()
    make_terrain_lit()
    make_error_material()
    surface = make_surface_master()
    make_swatches(surface)
    unreal.EditorAssetLibrary.save_directory(ROOT, False, True)
    unreal.log("Parapenting Level 1 material library created successfully")


if __name__ == "__main__":
    build_material_library()
